Traceback (most recent call last):
  File "/Users/n00002621/.local/share/virtualenvs/WFChemCookbook-hyZchOOL/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/n00002621/.local/share/virtualenvs/WFChemCookbook-hyZchOOL/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/n00002621/.local/share/virtualenvs/WFChemCookbook-hyZchOOL/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/n00002621/.local/share/virtualenvs/WFChemCookbook-hyZchOOL/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/n00002621/.local/share/virtualenvs/WFChemCookbook-hyZchOOL/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/n00002621/.local/share/virtualenvs/WFChemCookbook-hyZchOOL/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/n00002621/.local/share/virtualenvs/WFChemCookbook-hyZchOOL/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import a file of SMILES
smiles_list = []
with open('my_smiles.smi') as infile:
     for smi in infile:
            smiles_list.append(smi.rstrip()) # rstrip removes newline
print(smiles_list)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# Import a file of SMILES[39;00m
[1;32m      2[0m smiles_list [38;5;241m=[39m []
[0;32m----> 3[0m [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mmy_smiles.smi[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m infile:
[1;32m      4[0m      [38;5;28;01mfor[39;00m smi [38;5;129;01min[39;00m infile:
[1;32m      5[0m             smiles_list[38;5;241m.[39mappend(smi[38;5;241m.[39mrstrip()) [38;5;66;03m# rstrip removes newline[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'my_smiles.smi'
FileNotFoundError: [Errno 2] No such file or directory: 'my_smiles.smi'

