Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/IUPAC/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/IUPAC/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/IUPAC/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/IUPAC/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/IUPAC/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/IUPAC/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/IUPAC/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/IUPAC/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
""" For reporting of epsilon value corresponding to lambda max, we must first take the anitlog in this 
    example """

epsilon = np.exp(log_epsilon) # Create a variable and assign the antilog of log_epsilon 
                              # using numpys exp (exponential) method

arg_max = np.argmax(epsilon) # Use numpys arg max function to find the index of the largest y value
lambda_max = wavelength[arg_max] # Use this index to find the x value at max y

print(f"{lambda_max:.1f} nm") # Printing output to screen to 1 d.p including proper units
print(f'{associated_epsilon} L mol-1 cm-1') # Printing output to screen including units 

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 11[0m
[1;32m      8[0m lambda_max [38;5;241m=[39m wavelength[arg_max] [38;5;66;03m# Use this index to find the x value at max y[39;00m
[1;32m     10[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mlambda_max[38;5;132;01m:[39;00m[38;5;124m.1f[39m[38;5;132;01m}[39;00m[38;5;124m nm[39m[38;5;124m"[39m) [38;5;66;03m# Printing output to screen to 1 d.p including proper units[39;00m
[0;32m---> 11[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00m[43massociated_epsilon[49m[38;5;132;01m}[39;00m[38;5;124m L mol-1 cm-1[39m[38;5;124m'[39m) [38;5;66;03m# Printing output to screen including units [39;00m

[0;31mNameError[0m: name 'associated_epsilon' is not defined
NameError: name 'associated_epsilon' is not defined

